using System;
using System.Collections.Generic;

namespace CountryParse
{
    public class Country
    {
        private Country(string englishName, string threeLetterIsoLanguageName, string twoLetterIsoLanguageName)
        {
            EnglishName = englishName;
            ThreeLetterISOLanguageName = threeLetterIsoLanguageName;
            TwoLetterISOLanguageName = twoLetterIsoLanguageName;
        }

        public static Country Parse(string country)
        {
            if (TryParse(country, out Country result))
            {
                return result;
            }

            throw new FormatException("Input string could not be identified as a country.");
        }

        public static bool TryParse(string country, out Country result)
        {
            if (country == null)
            {
                throw new ArgumentNullException("Value cannot be null.", nameof(country));
            }

            if (CountriesByName.TryGetValue(country, out Func<Country> func))
            {
                result = func();
                return true;
            }

            if (CommonMixups.TryGetValue(country, out string actual))
            {
                result = CountriesByName[actual]();
                return true;
            }

            if (TwoLetterToName.TryGetValue(country, out string countryNameTwo))
            {
                result = CountriesByName[countryNameTwo]();
                return true;
            }

            if (ThreeLetterToName.TryGetValue(country, out string countryNameThree))
            {
                result = CountriesByName[countryNameThree]();
                return true;
            }

            result = null;
            return false;
        }

        public string EnglishName { get; }
        public string ThreeLetterISOLanguageName { get; }
        public string TwoLetterISOLanguageName { get; }

        private static Dictionary<string, Func<Country>> CountriesByName = new Dictionary<string, Func<Country>>
        {
            { "Afghanistan", () => {return new Country("Afghanistan", "AFG", "AF"); } },
            { "Åland Islands", () => {return new Country("Åland Islands", "ALA", "AX"); } },
            { "Albania", () => {return new Country("Albania", "ALB", "AL"); } },
            { "Algeria", () => {return new Country("Algeria", "DZA", "DZ"); } },
            { "American Samoa", () => {return new Country("American Samoa", "ASM", "AS"); } },
            { "Andorra", () => {return new Country("Andorra", "AND", "AD"); } },
            { "Angola", () => {return new Country("Angola", "AGO", "AO"); } },
            { "Anguilla", () => {return new Country("Anguilla", "AIA", "AI"); } },
            { "Antarctica", () => {return new Country("Antarctica", "ATA", "AQ"); } },
            { "Antigua and Barbuda", () => {return new Country("Antigua and Barbuda", "ATG", "AG"); } },
            { "Argentina", () => {return new Country("Argentina", "ARG", "AR"); } },
            { "Armenia", () => {return new Country("Armenia", "ARM", "AM"); } },
            { "Aruba", () => {return new Country("Aruba", "ABW", "AW"); } },
            { "Australia", () => {return new Country("Australia", "AUS", "AU"); } },
            { "Austria", () => {return new Country("Austria", "AUT", "AT"); } },
            { "Azerbaijan", () => {return new Country("Azerbaijan", "AZE", "AZ"); } },
            { "Bahamas", () => {return new Country("Bahamas", "BHS", "BS"); } },
            { "Bahrain", () => {return new Country("Bahrain", "BHR", "BH"); } },
            { "Bangladesh", () => {return new Country("Bangladesh", "BGD", "BD"); } },
            { "Barbados", () => {return new Country("Barbados", "BRB", "BB"); } },
            { "Belarus", () => {return new Country("Belarus", "BLR", "BY"); } },
            { "Belgium", () => {return new Country("Belgium", "BEL", "BE"); } },
            { "Belize", () => {return new Country("Belize", "BLZ", "BZ"); } },
            { "Benin", () => {return new Country("Benin", "BEN", "BJ"); } },
            { "Bermuda", () => {return new Country("Bermuda", "BMU", "BM"); } },
            { "Bhutan", () => {return new Country("Bhutan", "BTN", "BT"); } },
            { "Bolivia (Plurinational State of)", () => {return new Country("Bolivia (Plurinational State of)", "BOL", "BO"); } },
            { "Bonaire, Sint Eustatius and Saba", () => {return new Country("Bonaire, Sint Eustatius and Saba", "BES", "BQ"); } },
            { "Bosnia and Herzegovina", () => {return new Country("Bosnia and Herzegovina", "BIH", "BA"); } },
            { "Botswana", () => {return new Country("Botswana", "BWA", "BW"); } },
            { "Bouvet Island", () => {return new Country("Bouvet Island", "BVT", "BV"); } },
            { "Brazil", () => {return new Country("Brazil", "BRA", "BR"); } },
            { "British Indian Ocean Territory", () => {return new Country("British Indian Ocean Territory", "IOT", "IO"); } },
            { "Brunei Darussalam", () => {return new Country("Brunei Darussalam", "BRN", "BN"); } },
            { "Bulgaria", () => {return new Country("Bulgaria", "BGR", "BG"); } },
            { "Burkina Faso", () => {return new Country("Burkina Faso", "BFA", "BF"); } },
            { "Burundi", () => {return new Country("Burundi", "BDI", "BI"); } },
            { "Cabo Verde", () => {return new Country("Cabo Verde", "CPV", "CV"); } },
            { "Cambodia", () => {return new Country("Cambodia", "KHM", "KH"); } },
            { "Cameroon", () => {return new Country("Cameroon", "CMR", "CM"); } },
            { "Canada", () => {return new Country("Canada", "CAN", "CA"); } },
            { "Cayman Islands", () => {return new Country("Cayman Islands", "CYM", "KY"); } },
            { "Central African Republic", () => {return new Country("Central African Republic", "CAF", "CF"); } },
            { "Chad", () => {return new Country("Chad", "TCD", "TD"); } },
            { "Chile", () => {return new Country("Chile", "CHL", "CL"); } },
            { "China", () => {return new Country("China", "CHN", "CN"); } },
            { "Christmas Island", () => {return new Country("Christmas Island", "CXR", "CX"); } },
            { "Cocos (Keeling) Islands", () => {return new Country("Cocos (Keeling) Islands", "CCK", "CC"); } },
            { "Colombia", () => {return new Country("Colombia", "COL", "CO"); } },
            { "Comoros", () => {return new Country("Comoros", "COM", "KM"); } },
            { "Congo", () => {return new Country("Congo", "COG", "CG"); } },
            { "Congo (Democratic Republic of the)", () => {return new Country("Congo (Democratic Republic of the)", "COD", "CD"); } },
            { "Cook Islands", () => {return new Country("Cook Islands", "COK", "CK"); } },
            { "Costa Rica", () => {return new Country("Costa Rica", "CRI", "CR"); } },
            { "Côte d'Ivoire", () => {return new Country("Côte d'Ivoire", "CIV", "CI"); } },
            { "Croatia", () => {return new Country("Croatia", "HRV", "HR"); } },
            { "Cuba", () => {return new Country("Cuba", "CUB", "CU"); } },
            { "Curaçao", () => {return new Country("Curaçao", "CUW", "CW"); } },
            { "Cyprus", () => {return new Country("Cyprus", "CYP", "CY"); } },
            { "Czechia", () => {return new Country("Czechia", "CZE", "CZ"); } },
            { "Czech Republic", () => {return new Country("Czech Republic", "CZE", "CZ"); } },
            { "Denmark", () => {return new Country("Denmark", "DNK", "DK"); } },
            { "Djibouti", () => {return new Country("Djibouti", "DJI", "DJ"); } },
            { "Dominica", () => {return new Country("Dominica", "DMA", "DM"); } },
            { "Dominican Republic", () => {return new Country("Dominican Republic", "DOM", "DO"); } },
            { "Ecuador", () => {return new Country("Ecuador", "ECU", "EC"); } },
            { "Egypt", () => {return new Country("Egypt", "EGY", "EG"); } },
            { "El Salvador", () => {return new Country("El Salvador", "SLV", "SV"); } },
            { "Equatorial Guinea", () => {return new Country("Equatorial Guinea", "GNQ", "GQ"); } },
            { "Eritrea", () => {return new Country("Eritrea", "ERI", "ER"); } },
            { "Estonia", () => {return new Country("Estonia", "EST", "EE"); } },
            { "Ethiopia", () => {return new Country("Ethiopia", "ETH", "ET"); } },
            { "Falkland Islands (Malvinas)", () => {return new Country("Falkland Islands (Malvinas)", "FLK", "FK"); } },
            { "Faroe Islands", () => {return new Country("Faroe Islands", "FRO", "FO"); } },
            { "Fiji", () => {return new Country("Fiji", "FJI", "FJ"); } },
            { "Finland", () => {return new Country("Finland", "FIN", "FI"); } },
            { "France", () => {return new Country("France", "FRA", "FR"); } },
            { "French Guiana", () => {return new Country("French Guiana", "GUF", "GF"); } },
            { "French Polynesia", () => {return new Country("French Polynesia", "PYF", "PF"); } },
            { "French Southern Territories", () => {return new Country("French Southern Territories", "ATF", "TF"); } },
            { "Gabon", () => {return new Country("Gabon", "GAB", "GA"); } },
            { "Gambia", () => {return new Country("Gambia", "GMB", "GM"); } },
            { "Georgia", () => {return new Country("Georgia", "GEO", "GE"); } },
            { "Germany", () => {return new Country("Germany", "DEU", "DE"); } },
            { "Ghana", () => {return new Country("Ghana", "GHA", "GH"); } },
            { "Gibraltar", () => {return new Country("Gibraltar", "GIB", "GI"); } },
            { "Greece", () => {return new Country("Greece", "GRC", "GR"); } },
            { "Greenland", () => {return new Country("Greenland", "GRL", "GL"); } },
            { "Grenada", () => {return new Country("Grenada", "GRD", "GD"); } },
            { "Guadeloupe", () => {return new Country("Guadeloupe", "GLP", "GP"); } },
            { "Guam", () => {return new Country("Guam", "GUM", "GU"); } },
            { "Guatemala", () => {return new Country("Guatemala", "GTM", "GT"); } },
            { "Guernsey", () => {return new Country("Guernsey", "GGY", "GG"); } },
            { "Guinea", () => {return new Country("Guinea", "GIN", "GN"); } },
            { "Guinea-Bissau", () => {return new Country("Guinea-Bissau", "GNB", "GW"); } },
            { "Guyana", () => {return new Country("Guyana", "GUY", "GY"); } },
            { "Haiti", () => {return new Country("Haiti", "HTI", "HT"); } },
            { "Heard Island and McDonald Islands", () => {return new Country("Heard Island and McDonald Islands", "HMD", "HM"); } },
            { "Holy See", () => {return new Country("Holy See", "VAT", "VA"); } },
            { "Honduras", () => {return new Country("Honduras", "HND", "HN"); } },
            { "Hong Kong", () => {return new Country("Hong Kong", "HKG", "HK"); } },
            { "Hungary", () => {return new Country("Hungary", "HUN", "HU"); } },
            { "Iceland", () => {return new Country("Iceland", "ISL", "IS"); } },
            { "India", () => {return new Country("India", "IND", "IN"); } },
            { "Indonesia", () => {return new Country("Indonesia", "IDN", "ID"); } },
            { "Iran (Islamic Republic of)", () => {return new Country("Iran (Islamic Republic of)", "IRN", "IR"); } },
            { "Iraq", () => {return new Country("Iraq", "IRQ", "IQ"); } },
            { "Ireland", () => {return new Country("Ireland", "IRL", "IE"); } },
            { "Isle of Man", () => {return new Country("Isle of Man", "IMN", "IM"); } },
            { "Israel", () => {return new Country("Israel", "ISR", "IL"); } },
            { "Italy", () => {return new Country("Italy", "ITA", "IT"); } },
            { "Jamaica", () => {return new Country("Jamaica", "JAM", "JM"); } },
            { "Japan", () => {return new Country("Japan", "JPN", "JP"); } },
            { "Jersey", () => {return new Country("Jersey", "JEY", "JE"); } },
            { "Jordan", () => {return new Country("Jordan", "JOR", "JO"); } },
            { "Kazakhstan", () => {return new Country("Kazakhstan", "KAZ", "KZ"); } },
            { "Kenya", () => {return new Country("Kenya", "KEN", "KE"); } },
            { "Kiribati", () => {return new Country("Kiribati", "KIR", "KI"); } },
            { "Korea (Democratic People's Republic of)", () => {return new Country("Korea (Democratic People's Republic of)", "PRK", "KP"); } },
            { "Korea (Republic of)", () => {return new Country("Korea (Republic of)", "KOR", "KR"); } },
            { "Kuwait", () => {return new Country("Kuwait", "KWT", "KW"); } },
            { "Kyrgyzstan", () => {return new Country("Kyrgyzstan", "KGZ", "KG"); } },
            { "Lao People's Democratic Republic", () => {return new Country("Lao People's Democratic Republic", "LAO", "LA"); } },
            { "Latvia", () => {return new Country("Latvia", "LVA", "LV"); } },
            { "Lebanon", () => {return new Country("Lebanon", "LBN", "LB"); } },
            { "Lesotho", () => {return new Country("Lesotho", "LSO", "LS"); } },
            { "Liberia", () => {return new Country("Liberia", "LBR", "LR"); } },
            { "Libya", () => {return new Country("Libya", "LBY", "LY"); } },
            { "Liechtenstein", () => {return new Country("Liechtenstein", "LIE", "LI"); } },
            { "Lithuania", () => {return new Country("Lithuania", "LTU", "LT"); } },
            { "Luxembourg", () => {return new Country("Luxembourg", "LUX", "LU"); } },
            { "Macao", () => {return new Country("Macao", "MAC", "MO"); } },
            { "Macedonia (the former Yugoslav Republic of)", () => {return new Country("Macedonia (the former Yugoslav Republic of)", "MKD", "MK"); } },
            { "Madagascar", () => {return new Country("Madagascar", "MDG", "MG"); } },
            { "Malawi", () => {return new Country("Malawi", "MWI", "MW"); } },
            { "Malaysia", () => {return new Country("Malaysia", "MYS", "MY"); } },
            { "Maldives", () => {return new Country("Maldives", "MDV", "MV"); } },
            { "Mali", () => {return new Country("Mali", "MLI", "ML"); } },
            { "Malta", () => {return new Country("Malta", "MLT", "MT"); } },
            { "Marshall Islands", () => {return new Country("Marshall Islands", "MHL", "MH"); } },
            { "Martinique", () => {return new Country("Martinique", "MTQ", "MQ"); } },
            { "Mauritania", () => {return new Country("Mauritania", "MRT", "MR"); } },
            { "Mauritius", () => {return new Country("Mauritius", "MUS", "MU"); } },
            { "Mayotte", () => {return new Country("Mayotte", "MYT", "YT"); } },
            { "Mexico", () => {return new Country("Mexico", "MEX", "MX"); } },
            { "Micronesia (Federated States of)", () => {return new Country("Micronesia (Federated States of)", "FSM", "FM"); } },
            { "Moldova (Republic of)", () => {return new Country("Moldova (Republic of)", "MDA", "MD"); } },
            { "Monaco", () => {return new Country("Monaco", "MCO", "MC"); } },
            { "Mongolia", () => {return new Country("Mongolia", "MNG", "MN"); } },
            { "Montenegro", () => {return new Country("Montenegro", "MNE", "ME"); } },
            { "Montserrat", () => {return new Country("Montserrat", "MSR", "MS"); } },
            { "Morocco", () => {return new Country("Morocco", "MAR", "MA"); } },
            { "Mozambique", () => {return new Country("Mozambique", "MOZ", "MZ"); } },
            { "Myanmar", () => {return new Country("Myanmar", "MMR", "MM"); } },
            { "Namibia", () => {return new Country("Namibia", "NAM", "NA"); } },
            { "Nauru", () => {return new Country("Nauru", "NRU", "NR"); } },
            { "Nepal", () => {return new Country("Nepal", "NPL", "NP"); } },
            { "Netherlands", () => {return new Country("Netherlands", "NLD", "NL"); } },
            { "New Caledonia", () => {return new Country("New Caledonia", "NCL", "NC"); } },
            { "New Zealand", () => {return new Country("New Zealand", "NZL", "NZ"); } },
            { "Nicaragua", () => {return new Country("Nicaragua", "NIC", "NI"); } },
            { "Niger", () => {return new Country("Niger", "NER", "NE"); } },
            { "Nigeria", () => {return new Country("Nigeria", "NGA", "NG"); } },
            { "Niue", () => {return new Country("Niue", "NIU", "NU"); } },
            { "Norfolk Island", () => {return new Country("Norfolk Island", "NFK", "NF"); } },
            { "Northern Mariana Islands", () => {return new Country("Northern Mariana Islands", "MNP", "MP"); } },
            { "Norway", () => {return new Country("Norway", "NOR", "NO"); } },
            { "Oman", () => {return new Country("Oman", "OMN", "OM"); } },
            { "Pakistan", () => {return new Country("Pakistan", "PAK", "PK"); } },
            { "Palau", () => {return new Country("Palau", "PLW", "PW"); } },
            { "Palestine, State of", () => {return new Country("Palestine, State of", "PSE", "PS"); } },
            { "Panama", () => {return new Country("Panama", "PAN", "PA"); } },
            { "Papua New Guinea", () => {return new Country("Papua New Guinea", "PNG", "PG"); } },
            { "Paraguay", () => {return new Country("Paraguay", "PRY", "PY"); } },
            { "Peru", () => {return new Country("Peru", "PER", "PE"); } },
            { "Philippines", () => {return new Country("Philippines", "PHL", "PH"); } },
            { "Pitcairn", () => {return new Country("Pitcairn", "PCN", "PN"); } },
            { "Poland", () => {return new Country("Poland", "POL", "PL"); } },
            { "Portugal", () => {return new Country("Portugal", "PRT", "PT"); } },
            { "Puerto Rico", () => {return new Country("Puerto Rico", "PRI", "PR"); } },
            { "Qatar", () => {return new Country("Qatar", "QAT", "QA"); } },
            { "Réunion", () => {return new Country("Réunion", "REU", "RE"); } },
            { "Romania", () => {return new Country("Romania", "ROU", "RO"); } },
            { "Russian Federation", () => {return new Country("Russian Federation", "RUS", "RU"); } },
            { "Rwanda", () => {return new Country("Rwanda", "RWA", "RW"); } },
            { "Saint Barthélemy", () => {return new Country("Saint Barthélemy", "BLM", "BL"); } },
            { "Saint Helena, Ascension and Tristan da Cunha", () => {return new Country("Saint Helena, Ascension and Tristan da Cunha", "SHN", "SH"); } },
            { "Saint Kitts and Nevis", () => {return new Country("Saint Kitts and Nevis", "KNA", "KN"); } },
            { "Saint Lucia", () => {return new Country("Saint Lucia", "LCA", "LC"); } },
            { "Saint Martin (French part)", () => {return new Country("Saint Martin (French part)", "MAF", "MF"); } },
            { "Saint Pierre and Miquelon", () => {return new Country("Saint Pierre and Miquelon", "SPM", "PM"); } },
            { "Saint Vincent and the Grenadines", () => {return new Country("Saint Vincent and the Grenadines", "VCT", "VC"); } },
            { "Samoa", () => {return new Country("Samoa", "WSM", "WS"); } },
            { "San Marino", () => {return new Country("San Marino", "SMR", "SM"); } },
            { "Sao Tome and Principe", () => {return new Country("Sao Tome and Principe", "STP", "ST"); } },
            { "Saudi Arabia", () => {return new Country("Saudi Arabia", "SAU", "SA"); } },
            { "Senegal", () => {return new Country("Senegal", "SEN", "SN"); } },
            { "Serbia", () => {return new Country("Serbia", "SRB", "RS"); } },
            { "Seychelles", () => {return new Country("Seychelles", "SYC", "SC"); } },
            { "Sierra Leone", () => {return new Country("Sierra Leone", "SLE", "SL"); } },
            { "Singapore", () => {return new Country("Singapore", "SGP", "SG"); } },
            { "Sint Maarten (Dutch part)", () => {return new Country("Sint Maarten (Dutch part)", "SXM", "SX"); } },
            { "Slovakia", () => {return new Country("Slovakia", "SVK", "SK"); } },
            { "Slovenia", () => {return new Country("Slovenia", "SVN", "SI"); } },
            { "Solomon Islands", () => {return new Country("Solomon Islands", "SLB", "SB"); } },
            { "Somalia", () => {return new Country("Somalia", "SOM", "SO"); } },
            { "South Africa", () => {return new Country("South Africa", "ZAF", "ZA"); } },
            { "South Georgia and the South Sandwich Islands", () => {return new Country("South Georgia and the South Sandwich Islands", "SGS", "GS"); } },
            { "South Sudan", () => {return new Country("South Sudan", "SSD", "SS"); } },
            { "Spain", () => {return new Country("Spain", "ESP", "ES"); } },
            { "Sri Lanka", () => {return new Country("Sri Lanka", "LKA", "LK"); } },
            { "Sudan", () => {return new Country("Sudan", "SDN", "SD"); } },
            { "Suriname", () => {return new Country("Suriname", "SUR", "SR"); } },
            { "Svalbard and Jan Mayen", () => {return new Country("Svalbard and Jan Mayen", "SJM", "SJ"); } },
            { "Swaziland", () => {return new Country("Swaziland", "SWZ", "SZ"); } },
            { "Sweden", () => {return new Country("Sweden", "SWE", "SE"); } },
            { "Switzerland", () => {return new Country("Switzerland", "CHE", "CH"); } },
            { "Syrian Arab Republic", () => {return new Country("Syrian Arab Republic", "SYR", "SY"); } },
            { "Taiwan, Province of China", () => {return new Country("Taiwan, Province of China", "TWN", "TW"); } },
            { "Tajikistan", () => {return new Country("Tajikistan", "TJK", "TJ"); } },
            { "Tanzania, United Republic of", () => {return new Country("Tanzania, United Republic of", "TZA", "TZ"); } },
            { "Thailand", () => {return new Country("Thailand", "THA", "TH"); } },
            { "Timor-Leste", () => {return new Country("Timor-Leste", "TLS", "TL"); } },
            { "Togo", () => {return new Country("Togo", "TGO", "TG"); } },
            { "Tokelau", () => {return new Country("Tokelau", "TKL", "TK"); } },
            { "Tonga", () => {return new Country("Tonga", "TON", "TO"); } },
            { "Trinidad and Tobago", () => {return new Country("Trinidad and Tobago", "TTO", "TT"); } },
            { "Tunisia", () => {return new Country("Tunisia", "TUN", "TN"); } },
            { "Turkey", () => {return new Country("Turkey", "TUR", "TR"); } },
            { "Turkmenistan", () => {return new Country("Turkmenistan", "TKM", "TM"); } },
            { "Turks and Caicos Islands", () => {return new Country("Turks and Caicos Islands", "TCA", "TC"); } },
            { "Tuvalu", () => {return new Country("Tuvalu", "TUV", "TV"); } },
            { "Uganda", () => {return new Country("Uganda", "UGA", "UG"); } },
            { "Ukraine", () => {return new Country("Ukraine", "UKR", "UA"); } },
            { "United Arab Emirates", () => {return new Country("United Arab Emirates", "ARE", "AE"); } },
            { "United Kingdom of Great Britain and Northern Ireland", () => {return new Country("United Kingdom of Great Britain and Northern Ireland", "GBR", "GB"); } },
            { "United States of America", () => {return new Country("United States of America", "USA", "US"); } },
            { "United States Minor Outlying Islands", () => {return new Country("United States Minor Outlying Islands", "UMI", "UM"); } },
            { "Uruguay", () => {return new Country("Uruguay", "URY", "UY"); } },
            { "Uzbekistan", () => {return new Country("Uzbekistan", "UZB", "UZ"); } },
            { "Vanuatu", () => {return new Country("Vanuatu", "VUT", "VU"); } },
            { "Venezuela (Bolivarian Republic of)", () => {return new Country("Venezuela (Bolivarian Republic of)", "VEN", "VE"); } },
            { "Viet Nam", () => {return new Country("Viet Nam", "VNM", "VN"); } },
            { "Virgin Islands (British)", () => {return new Country("Virgin Islands (British)", "VGB", "VG"); } },
            { "Virgin Islands (U.S.)", () => {return new Country("Virgin Islands (U.S.)", "VIR", "VI"); } },
            { "Wallis and Futuna", () => {return new Country("Wallis and Futuna", "WLF", "WF"); } },
            { "Western Sahara", () => {return new Country("Western Sahara", "ESH", "EH"); } },
            { "Yemen", () => {return new Country("Yemen", "YEM", "YE"); } },
            { "Zambia", () => {return new Country("Zambia", "ZMB", "ZM"); } },
            { "Zimbabwe", () => {return new Country("Zimbabwe", "ZWE", "ZW"); } }
        };

        private static Dictionary<string, string> ThreeLetterToName = new Dictionary<string, string>
        {
            { "AFG", "Afghanistan" },
            { "ALA", "Åland Islands" },
            { "ALB", "Albania" },
            { "DZA", "Algeria" },
            { "ASM", "American Samoa" },
            { "AND", "Andorra" },
            { "AGO", "Angola" },
            { "AIA", "Anguilla" },
            { "ATA", "Antarctica" },
            { "ATG", "Antigua and Barbuda" },
            { "ARG", "Argentina" },
            { "ARM", "Armenia" },
            { "ABW", "Aruba" },
            { "AUS", "Australia" },
            { "AUT", "Austria" },
            { "AZE", "Azerbaijan" },
            { "BHS", "Bahamas" },
            { "BHR", "Bahrain" },
            { "BGD", "Bangladesh" },
            { "BRB", "Barbados" },
            { "BLR", "Belarus" },
            { "BEL", "Belgium" },
            { "BLZ", "Belize" },
            { "BEN", "Benin" },
            { "BMU", "Bermuda" },
            { "BTN", "Bhutan" },
            { "BOL", "Bolivia (Plurinational State of)" },
            { "BES", "Bonaire, Sint Eustatius and Saba" },
            { "BIH", "Bosnia and Herzegovina" },
            { "BWA", "Botswana" },
            { "BVT", "Bouvet Island" },
            { "BRA", "Brazil" },
            { "IOT", "British Indian Ocean Territory" },
            { "BRN", "Brunei Darussalam" },
            { "BGR", "Bulgaria" },
            { "BFA", "Burkina Faso" },
            { "BDI", "Burundi" },
            { "CPV", "Cabo Verde" },
            { "KHM", "Cambodia" },
            { "CMR", "Cameroon" },
            { "CAN", "Canada" },
            { "CYM", "Cayman Islands" },
            { "CAF", "Central African Republic" },
            { "TCD", "Chad" },
            { "CHL", "Chile" },
            { "CHN", "China" },
            { "CXR", "Christmas Island" },
            { "CCK", "Cocos (Keeling) Islands" },
            { "COL", "Colombia" },
            { "COM", "Comoros" },
            { "COG", "Congo" },
            { "COD", "Congo (Democratic Republic of the)" },
            { "COK", "Cook Islands" },
            { "CRI", "Costa Rica" },
            { "CIV", "Côte d'Ivoire" },
            { "HRV", "Croatia" },
            { "CUB", "Cuba" },
            { "CUW", "Curaçao" },
            { "CYP", "Cyprus" },
            { "CZE", "Czech Republic" },
            { "DNK", "Denmark" },
            { "DJI", "Djibouti" },
            { "DMA", "Dominica" },
            { "DOM", "Dominican Republic" },
            { "ECU", "Ecuador" },
            { "EGY", "Egypt" },
            { "SLV", "El Salvador" },
            { "GNQ", "Equatorial Guinea" },
            { "ERI", "Eritrea" },
            { "EST", "Estonia" },
            { "ETH", "Ethiopia" },
            { "FLK", "Falkland Islands (Malvinas)" },
            { "FRO", "Faroe Islands" },
            { "FJI", "Fiji" },
            { "FIN", "Finland" },
            { "FRA", "France" },
            { "GUF", "French Guiana" },
            { "PYF", "French Polynesia" },
            { "ATF", "French Southern Territories" },
            { "GAB", "Gabon" },
            { "GMB", "Gambia" },
            { "GEO", "Georgia" },
            { "DEU", "Germany" },
            { "GHA", "Ghana" },
            { "GIB", "Gibraltar" },
            { "GRC", "Greece" },
            { "GRL", "Greenland" },
            { "GRD", "Grenada" },
            { "GLP", "Guadeloupe" },
            { "GUM", "Guam" },
            { "GTM", "Guatemala" },
            { "GGY", "Guernsey" },
            { "GIN", "Guinea" },
            { "GNB", "Guinea-Bissau" },
            { "GUY", "Guyana" },
            { "HTI", "Haiti" },
            { "HMD", "Heard Island and McDonald Islands" },
            { "VAT", "Holy See" },
            { "HND", "Honduras" },
            { "HKG", "Hong Kong" },
            { "HUN", "Hungary" },
            { "ISL", "Iceland" },
            { "IND", "India" },
            { "IDN", "Indonesia" },
            { "IRN", "Iran (Islamic Republic of)" },
            { "IRQ", "Iraq" },
            { "IRL", "Ireland" },
            { "IMN", "Isle of Man" },
            { "ISR", "Israel" },
            { "ITA", "Italy" },
            { "JAM", "Jamaica" },
            { "JPN", "Japan" },
            { "JEY", "Jersey" },
            { "JOR", "Jordan" },
            { "KAZ", "Kazakhstan" },
            { "KEN", "Kenya" },
            { "KIR", "Kiribati" },
            { "PRK", "Korea (Democratic People's Republic of)" },
            { "KOR", "Korea (Republic of)" },
            { "KWT", "Kuwait" },
            { "KGZ", "Kyrgyzstan" },
            { "LAO", "Lao People's Democratic Republic" },
            { "LVA", "Latvia" },
            { "LBN", "Lebanon" },
            { "LSO", "Lesotho" },
            { "LBR", "Liberia" },
            { "LBY", "Libya" },
            { "LIE", "Liechtenstein" },
            { "LTU", "Lithuania" },
            { "LUX", "Luxembourg" },
            { "MAC", "Macao" },
            { "MKD", "Macedonia (the former Yugoslav Republic of)" },
            { "MDG", "Madagascar" },
            { "MWI", "Malawi" },
            { "MYS", "Malaysia" },
            { "MDV", "Maldives" },
            { "MLI", "Mali" },
            { "MLT", "Malta" },
            { "MHL", "Marshall Islands" },
            { "MTQ", "Martinique" },
            { "MRT", "Mauritania" },
            { "MUS", "Mauritius" },
            { "MYT", "Mayotte" },
            { "MEX", "Mexico" },
            { "FSM", "Micronesia (Federated States of)" },
            { "MDA", "Moldova (Republic of)" },
            { "MCO", "Monaco" },
            { "MNG", "Mongolia" },
            { "MNE", "Montenegro" },
            { "MSR", "Montserrat" },
            { "MAR", "Morocco" },
            { "MOZ", "Mozambique" },
            { "MMR", "Myanmar" },
            { "NAM", "Namibia" },
            { "NRU", "Nauru" },
            { "NPL", "Nepal" },
            { "NLD", "Netherlands" },
            { "NCL", "New Caledonia" },
            { "NZL", "New Zealand" },
            { "NIC", "Nicaragua" },
            { "NER", "Niger" },
            { "NGA", "Nigeria" },
            { "NIU", "Niue" },
            { "NFK", "Norfolk Island" },
            { "MNP", "Northern Mariana Islands" },
            { "NOR", "Norway" },
            { "OMN", "Oman" },
            { "PAK", "Pakistan" },
            { "PLW", "Palau" },
            { "PSE", "Palestine, State of" },
            { "PAN", "Panama" },
            { "PNG", "Papua New Guinea" },
            { "PRY", "Paraguay" },
            { "PER", "Peru" },
            { "PHL", "Philippines" },
            { "PCN", "Pitcairn" },
            { "POL", "Poland" },
            { "PRT", "Portugal" },
            { "PRI", "Puerto Rico" },
            { "QAT", "Qatar" },
            { "REU", "Réunion" },
            { "ROU", "Romania" },
            { "RUS", "Russian Federation" },
            { "RWA", "Rwanda" },
            { "BLM", "Saint Barthélemy" },
            { "SHN", "Saint Helena, Ascension and Tristan da Cunha" },
            { "KNA", "Saint Kitts and Nevis" },
            { "LCA", "Saint Lucia" },
            { "MAF", "Saint Martin (French part)" },
            { "SPM", "Saint Pierre and Miquelon" },
            { "VCT", "Saint Vincent and the Grenadines" },
            { "WSM", "Samoa" },
            { "SMR", "San Marino" },
            { "STP", "Sao Tome and Principe" },
            { "SAU", "Saudi Arabia" },
            { "SEN", "Senegal" },
            { "SRB", "Serbia" },
            { "SYC", "Seychelles" },
            { "SLE", "Sierra Leone" },
            { "SGP", "Singapore" },
            { "SXM", "Sint Maarten (Dutch part)" },
            { "SVK", "Slovakia" },
            { "SVN", "Slovenia" },
            { "SLB", "Solomon Islands" },
            { "SOM", "Somalia" },
            { "ZAF", "South Africa" },
            { "SGS", "South Georgia and the South Sandwich Islands" },
            { "SSD", "South Sudan" },
            { "ESP", "Spain" },
            { "LKA", "Sri Lanka" },
            { "SDN", "Sudan" },
            { "SUR", "Suriname" },
            { "SJM", "Svalbard and Jan Mayen" },
            { "SWZ", "Swaziland" },
            { "SWE", "Sweden" },
            { "CHE", "Switzerland" },
            { "SYR", "Syrian Arab Republic" },
            { "TWN", "Taiwan, Province of China" },
            { "TJK", "Tajikistan" },
            { "TZA", "Tanzania, United Republic of" },
            { "THA", "Thailand" },
            { "TLS", "Timor-Leste" },
            { "TGO", "Togo" },
            { "TKL", "Tokelau" },
            { "TON", "Tonga" },
            { "TTO", "Trinidad and Tobago" },
            { "TUN", "Tunisia" },
            { "TUR", "Turkey" },
            { "TKM", "Turkmenistan" },
            { "TCA", "Turks and Caicos Islands" },
            { "TUV", "Tuvalu" },
            { "UGA", "Uganda" },
            { "UKR", "Ukraine" },
            { "ARE", "United Arab Emirates" },
            { "GBR", "United Kingdom of Great Britain and Northern Ireland" },
            { "USA", "United States of America" },
            { "UMI", "United States Minor Outlying Islands" },
            { "URY", "Uruguay" },
            { "UZB", "Uzbekistan" },
            { "VUT", "Vanuatu" },
            { "VEN", "Venezuela (Bolivarian Republic of)" },
            { "VNM", "Viet Nam" },
            { "VGB", "Virgin Islands (British)" },
            { "VIR", "Virgin Islands (U.S.)" },
            { "WLF", "Wallis and Futuna" },
            { "ESH", "Western Sahara" },
            { "YEM", "Yemen" },
            { "ZMB", "Zambia" },
            { "ZWE", "Zimbabwe" }
        };

        private static Dictionary<string, string> TwoLetterToName = new Dictionary<string, string>
        {
            { "AF", "Afghanistan" },
            { "AX", "Åland Islands" },
            { "AL", "Albania" },
            { "DZ", "Algeria" },
            { "AS", "American Samoa" },
            { "AD", "Andorra" },
            { "AO", "Angola" },
            { "AI", "Anguilla" },
            { "AQ", "Antarctica" },
            { "AG", "Antigua and Barbuda" },
            { "AR", "Argentina" },
            { "AM", "Armenia" },
            { "AW", "Aruba" },
            { "AU", "Australia" },
            { "AT", "Austria" },
            { "AZ", "Azerbaijan" },
            { "BS", "Bahamas" },
            { "BH", "Bahrain" },
            { "BD", "Bangladesh" },
            { "BB", "Barbados" },
            { "BY", "Belarus" },
            { "BE", "Belgium" },
            { "BZ", "Belize" },
            { "BJ", "Benin" },
            { "BM", "Bermuda" },
            { "BT", "Bhutan" },
            { "BO", "Bolivia (Plurinational State of)" },
            { "BQ", "Bonaire, Sint Eustatius and Saba" },
            { "BA", "Bosnia and Herzegovina" },
            { "BW", "Botswana" },
            { "BV", "Bouvet Island" },
            { "BR", "Brazil" },
            { "IO", "British Indian Ocean Territory" },
            { "BN", "Brunei Darussalam" },
            { "BG", "Bulgaria" },
            { "BF", "Burkina Faso" },
            { "BI", "Burundi" },
            { "CV", "Cabo Verde" },
            { "KH", "Cambodia" },
            { "CM", "Cameroon" },
            { "CA", "Canada" },
            { "KY", "Cayman Islands" },
            { "CF", "Central African Republic" },
            { "TD", "Chad" },
            { "CL", "Chile" },
            { "CN", "China" },
            { "CX", "Christmas Island" },
            { "CC", "Cocos (Keeling) Islands" },
            { "CO", "Colombia" },
            { "KM", "Comoros" },
            { "CG", "Congo" },
            { "CD", "Congo (Democratic Republic of the)" },
            { "CK", "Cook Islands" },
            { "CR", "Costa Rica" },
            { "CI", "Côte d'Ivoire" },
            { "HR", "Croatia" },
            { "CU", "Cuba" },
            { "CW", "Curaçao" },
            { "CY", "Cyprus" },
            { "CZ", "Czech Republic" },
            { "DK", "Denmark" },
            { "DJ", "Djibouti" },
            { "DM", "Dominica" },
            { "DO", "Dominican Republic" },
            { "EC", "Ecuador" },
            { "EG", "Egypt" },
            { "SV", "El Salvador" },
            { "GQ", "Equatorial Guinea" },
            { "ER", "Eritrea" },
            { "EE", "Estonia" },
            { "ET", "Ethiopia" },
            { "FK", "Falkland Islands (Malvinas)" },
            { "FO", "Faroe Islands" },
            { "FJ", "Fiji" },
            { "FI", "Finland" },
            { "FR", "France" },
            { "GF", "French Guiana" },
            { "PF", "French Polynesia" },
            { "TF", "French Southern Territories" },
            { "GA", "Gabon" },
            { "GM", "Gambia" },
            { "GE", "Georgia" },
            { "DE", "Germany" },
            { "GH", "Ghana" },
            { "GI", "Gibraltar" },
            { "GR", "Greece" },
            { "GL", "Greenland" },
            { "GD", "Grenada" },
            { "GP", "Guadeloupe" },
            { "GU", "Guam" },
            { "GT", "Guatemala" },
            { "GG", "Guernsey" },
            { "GN", "Guinea" },
            { "GW", "Guinea-Bissau" },
            { "GY", "Guyana" },
            { "HT", "Haiti" },
            { "HM", "Heard Island and McDonald Islands" },
            { "VA", "Holy See" },
            { "HN", "Honduras" },
            { "HK", "Hong Kong" },
            { "HU", "Hungary" },
            { "IS", "Iceland" },
            { "IN", "India" },
            { "ID", "Indonesia" },
            { "IR", "Iran (Islamic Republic of)" },
            { "IQ", "Iraq" },
            { "IE", "Ireland" },
            { "IM", "Isle of Man" },
            { "IL", "Israel" },
            { "IT", "Italy" },
            { "JM", "Jamaica" },
            { "JP", "Japan" },
            { "JE", "Jersey" },
            { "JO", "Jordan" },
            { "KZ", "Kazakhstan" },
            { "KE", "Kenya" },
            { "KI", "Kiribati" },
            { "KP", "Korea (Democratic People's Republic of)" },
            { "KR", "Korea (Republic of)" },
            { "KW", "Kuwait" },
            { "KG", "Kyrgyzstan" },
            { "LA", "Lao People's Democratic Republic" },
            { "LV", "Latvia" },
            { "LB", "Lebanon" },
            { "LS", "Lesotho" },
            { "LR", "Liberia" },
            { "LY", "Libya" },
            { "LI", "Liechtenstein" },
            { "LT", "Lithuania" },
            { "LU", "Luxembourg" },
            { "MO", "Macao" },
            { "MK", "Macedonia (the former Yugoslav Republic of)" },
            { "MG", "Madagascar" },
            { "MW", "Malawi" },
            { "MY", "Malaysia" },
            { "MV", "Maldives" },
            { "ML", "Mali" },
            { "MT", "Malta" },
            { "MH", "Marshall Islands" },
            { "MQ", "Martinique" },
            { "MR", "Mauritania" },
            { "MU", "Mauritius" },
            { "YT", "Mayotte" },
            { "MX", "Mexico" },
            { "FM", "Micronesia (Federated States of)" },
            { "MD", "Moldova (Republic of)" },
            { "MC", "Monaco" },
            { "MN", "Mongolia" },
            { "ME", "Montenegro" },
            { "MS", "Montserrat" },
            { "MA", "Morocco" },
            { "MZ", "Mozambique" },
            { "MM", "Myanmar" },
            { "NA", "Namibia" },
            { "NR", "Nauru" },
            { "NP", "Nepal" },
            { "NL", "Netherlands" },
            { "NC", "New Caledonia" },
            { "NZ", "New Zealand" },
            { "NI", "Nicaragua" },
            { "NE", "Niger" },
            { "NG", "Nigeria" },
            { "NU", "Niue" },
            { "NF", "Norfolk Island" },
            { "MP", "Northern Mariana Islands" },
            { "NO", "Norway" },
            { "OM", "Oman" },
            { "PK", "Pakistan" },
            { "PW", "Palau" },
            { "PS", "Palestine, State of" },
            { "PA", "Panama" },
            { "PG", "Papua New Guinea" },
            { "PY", "Paraguay" },
            { "PE", "Peru" },
            { "PH", "Philippines" },
            { "PN", "Pitcairn" },
            { "PL", "Poland" },
            { "PT", "Portugal" },
            { "PR", "Puerto Rico" },
            { "QA", "Qatar" },
            { "RE", "Réunion" },
            { "RO", "Romania" },
            { "RU", "Russian Federation" },
            { "RW", "Rwanda" },
            { "BL", "Saint Barthélemy" },
            { "SH", "Saint Helena, Ascension and Tristan da Cunha" },
            { "KN", "Saint Kitts and Nevis" },
            { "LC", "Saint Lucia" },
            { "MF", "Saint Martin (French part)" },
            { "PM", "Saint Pierre and Miquelon" },
            { "VC", "Saint Vincent and the Grenadines" },
            { "WS", "Samoa" },
            { "SM", "San Marino" },
            { "ST", "Sao Tome and Principe" },
            { "SA", "Saudi Arabia" },
            { "SN", "Senegal" },
            { "RS", "Serbia" },
            { "SC", "Seychelles" },
            { "SL", "Sierra Leone" },
            { "SG", "Singapore" },
            { "SX", "Sint Maarten (Dutch part)" },
            { "SK", "Slovakia" },
            { "SI", "Slovenia" },
            { "SB", "Solomon Islands" },
            { "SO", "Somalia" },
            { "ZA", "South Africa" },
            { "GS", "South Georgia and the South Sandwich Islands" },
            { "SS", "South Sudan" },
            { "ES", "Spain" },
            { "LK", "Sri Lanka" },
            { "SD", "Sudan" },
            { "SR", "Suriname" },
            { "SJ", "Svalbard and Jan Mayen" },
            { "SZ", "Swaziland" },
            { "SE", "Sweden" },
            { "CH", "Switzerland" },
            { "SY", "Syrian Arab Republic" },
            { "TW", "Taiwan, Province of China" },
            { "TJ", "Tajikistan" },
            { "TZ", "Tanzania, United Republic of" },
            { "TH", "Thailand" },
            { "TL", "Timor-Leste" },
            { "TG", "Togo" },
            { "TK", "Tokelau" },
            { "TO", "Tonga" },
            { "TT", "Trinidad and Tobago" },
            { "TN", "Tunisia" },
            { "TR", "Turkey" },
            { "TM", "Turkmenistan" },
            { "TC", "Turks and Caicos Islands" },
            { "TV", "Tuvalu" },
            { "UG", "Uganda" },
            { "UA", "Ukraine" },
            { "AE", "United Arab Emirates" },
            { "GB", "United Kingdom of Great Britain and Northern Ireland" },
            { "US", "United States of America" },
            { "UM", "United States Minor Outlying Islands" },
            { "UY", "Uruguay" },
            { "UZ", "Uzbekistan" },
            { "VU", "Vanuatu" },
            { "VE", "Venezuela (Bolivarian Republic of)" },
            { "VN", "Viet Nam" },
            { "VG", "Virgin Islands (British)" },
            { "VI", "Virgin Islands (U.S.)" },
            { "WF", "Wallis and Futuna" },
            { "EH", "Western Sahara" },
            { "YE", "Yemen" },
            { "ZM", "Zambia" },
            { "ZW", "Zimbabwe" }
        };

        private static Dictionary<string, string> CommonMixups = new Dictionary<string, string>
        {
            {"Macao SAR","Macao" },
            {"Vietnam","Viet Nam" },
            {"Moldova","Moldova (Republic of)" },
            {"Brunei","Brunei Darussalam" },
            {"Macedonia, FYRO","Macedonia (the former Yugoslav Republic of)" },
            {"Laos","Lao People's Democratic Republic" },
            {"Korea","Korea (Republic of)" },
            {"Côte d’Ivoire","Côte d'Ivoire" },
            {"Congo (DRC)","Congo (Democratic Republic of the)" },
            {"Iran","Iran (Islamic Republic of)" },
            {"Venezuela","Venezuela (Bolivarian Republic of)" },
            {"Bolivia","Bolivia (Plurinational State of)" },
            {"Hong Kong SAR","Hong Kong" },
            {"United Kingdom","United Kingdom of Great Britain and Northern Ireland" },
            {"United States","United States of America" },
            {"Russia","Russian Federation" },
            {"Syria","Syrian Arab Republic" },
            {"Taiwan","Taiwan, Province of China" },
        };
    }
}
